replicaCount: 2

image:
  repository: chauhanneru877/gitops-platform
  tag: "v1.0.1"

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

app:
  environment: staging
