apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gitops-staging
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mtotech/production-grade-gitops-platform.git
    targetRevision: main
    path: helm/gitops-platform

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
